name: バグ報告
description: Kubernetesの操作中に発生したバグを報告してください
labels: kind/bug
body:
  - type: textarea
    id: problem
    attributes:
      label: どのような問題が発生しましたか？
      description: |
        可能な限り詳細な情報を記入してください。不十分な情報の場合、対応が遅れる可能性があります。
        この問題がセキュリティに関係する場合は、https://kubernetes.io/security から非公開で報告してください。
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 本来はどのような動作を期待していましたか？
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: 最小かつ正確な再現手順を教えてください
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: その他に知っておくべきことがあれば記載してください

  - type: textarea
    id: kubeVersion
    attributes:
      label: Kubernetes のバージョン
      value: |
        <details>

        ```console
        $ kubectl version
        # 出力をここに貼り付けてください
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: cloudProvider
    attributes:
      label: クラウドプロバイダー
      value: |
        <details>

        </details>
    validations:
      required: true

  - type: textarea
    id: osVersion
    attributes:
      label: OS のバージョン
      value: |
        <details>

        ```console
        # Linux の場合:
        $ cat /etc/os-release
        # 出力をここに貼り付けてください
        $ uname -a
        # 出力をここに貼り付けてください

        # Windows の場合:
        C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
        # 出力をここに貼り付けてください
        ```

        </details>

  - type: textarea
    id: installer
    attributes:
      label: インストールに使用したツール
      value: |
        <details>

        </details>

  - type: textarea
    id: runtime
    attributes:
      label: コンテナランタイム（CRI）とそのバージョン（該当する場合）
      value: |
        <details>

        </details>

  - type: textarea
    id: plugins
    attributes:
      label: 関連するプラグイン（CNI, CSIなど）とそのバージョン（該当する場合）
      value: |
        <details>

        </details>
