name: バグ報告
description: アプリケーションで発生した不具合を報告します
labels: [bug]
body:
  - type: textarea
    id: problem
    attributes:
      label: どのような問題が発生しましたか？
      description: >
        できるだけ詳しく記述してください。不明確な報告は対応が遅れる可能性があります。
        ※ セキュリティ関連の内容は公開せず、別途管理者に連絡してください。
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 本来どうなることを期待していましたか？
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: 再現手順（できるだけ最小・正確に記載）
      placeholder: |
        1. 〇〇画面を開く  
        2. ✕✕をクリック  
        3. エラーが表示される
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: その他補足情報

  - type: textarea
    id: appVersion
    attributes:
      label: アプリのバージョン情報
      value: |
        <details>

        ```console
        $ app --version
        # 出力を貼り付けてください
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 使用環境（OS、ブラウザ、端末など）
      value: |
        <details>

        ```console
        # Linux の場合:
        $ cat /etc/os-release
        $ uname -a

        # macOS の場合:
        $ sw_vers

        # Windows の場合:
        C:\> systeminfo
        ```

        </details>

  - type: textarea
    id: installMethod
    attributes:
      label: インストール方法（該当する場合）

  - type: textarea
    id: runtime
    attributes:
      label: 実行環境（例: Node.js, Docker, Pythonバージョンなど）

  - type: textarea
    id: plugins
    attributes:
      label: 関連プラグインやライブラリのバージョン（該当する場合）
